### ISSUE TITLE
Does not work with ES2015 syntax!

### ISSUE THREAD

**Issue by bzkdjc** [caiguanhao/js-obfuscator#13]
![2016-08-29 00-13-39](https://cloud.githubusercontent.com/assets/13347655/18037889/b52939a6-6d7d-11e6-83a2-b6d9da8b2289.png)
Works very well with traditional JS!
But, I get `JScriptCodeDom.CodeParseException` errors (e.g. `=>` operator gives `Unexpected Operator` fatal error) for newer JS syntax.

**Comment by caiguanhao** [comment]
The [JavaScript Obfuscator](http://javascriptobfuscator.com/Javascript-Obfuscator.aspx) accepts ES5 code. You can transforms your code from ES6 to ES5 and then obfuscate them.

**Comment by bzkdjc** [comment]
I see. 
Anyway, Thank you!
