### ISSUE TITLE
undefined in file(s) after jsobfuscate

### ISSUE THREAD

**Issue by progknife** [caiguanhao/js-obfuscator#17]
Javascript files generated after js-obfuscator in Grunt results in "undefined" text in the file. Also tested with CLI:

```
$ jsobfuscate
Type or paste JavaScript code and then press Ctrl-D to obfuscate.
function foo() { return 1; }
undefined
```

**Comment by caiguanhao** [comment]
Thanks. Problem fixed and you can download the latest version.

**Comment by progknife** [comment]
Confirmed that it works! Thank you very much.
