### ISSUE TITLE
Parse error on self calling function marked with (...)

### ISSUE THREAD

**Issue by redaxmedia** [caiguanhao/js-obfuscator#6]
Working:

<pre>function (root) {

}(this);</pre>

Not working:

<pre>(function (root) {

}(this));</pre>

**Comment by caiguanhao** [comment]
maybe:
```js
(function (root) {

})(this);
```
is right?

you can try your code on http://www.javascriptobfuscator.com/Javascript-Obfuscator.aspx first

**Comment by redaxmedia** [comment]
Correct, but I have a third party library here that does it the wrong way^^

**Comment by redaxmedia** [comment]
Response of the third party maintainer: https://github.com/blueimp/JavaScript-MD5/pull/11#issuecomment-124573652

**Comment by caiguanhao** [comment]
the js-obfuscator may be using a stricter syntax check, to fix this problem, either you can change the code or uglify the script first and then obfuscate it. uglify-js would generate the code with the right syntax like this `(function ($) { ... })(this);`.

**Comment by redaxmedia** [comment]
Well, one person points the problem to another. It is valid Javascript so your script should handle it... mhh

**Comment by caiguanhao** [comment]
this can't be done, this script is simply to send your code to www.javascriptobfuscator.com and give you the response from that website, it won't do anything else

**Comment by redaxmedia** [comment]
Okay, I thought this is a standalone application that runs local.
