### ISSUE TITLE
Multiple files obfuscated but then combined into a single file

### ISSUE THREAD

**Issue by dazzayou** [caiguanhao/js-obfuscator#7]
Hi Guan Hao

I have multiple directories, each containing multiple files that I want to obfuscate. Is it possible to have each file's obfuscated code saved separately (separate destinations), rather than being combined into one giant file? 

At the moment I have:
   files: {
      'obfuscated_dest/dest.js': [
         './*.js'
      ]
   }

This obfuscates every file in the root directory, but them combines all the code into a single giant dest.js file. Is there a way to have js-obfuscator keep each obfuscated file separate?

**Comment by caiguanhao** [comment]
You can do it with some tricks:

```js
module.exports = function(grunt) {

  grunt.initConfig({
    jsObfuscate: {
      options: {
        replaceNames: true
      }
    }
  });

  var path = require('path');
  var configs = grunt.config.get('jsObfuscate');
  var jsFiles = grunt.file.expand(['src/**/*.js']);
  jsFiles.forEach(function (file) {
    configs[path.join('dist', path.basename(file))] = file;
  });
  grunt.config.set('jsObfuscate', configs);

  grunt.loadNpmTasks('js-obfuscator');

  grunt.registerTask('default', [
    'jsObfuscate'
  ]);

};
```
