### ISSUE TITLE
getting [TypeError: Cannot read property '0' of undefined] error

### ISSUE THREAD

**Issue by gansanz** [caiguanhao/js-obfuscator#8]
Hello,

when I execute the following script I get [TypeError: Cannot read property '0' of undefined] error

var jsObfuscator = require('js-obfuscator');

var script = 'Array.prototype.diff = function(a) {' +
'  return this.filter(function(i) {return a.indexOf(i) === -1;});' +
'};';

var options = {
  keepLinefeeds:      true,
  keepIndentations:   true,
  encodeStrings:      true,
  encodeNumbers:      true,
  moveStrings:        true,
  replaceNames:       true,
  variableExclusions: [ '^_get_', '^_set_', '^_mtd_' ]
};

jsObfuscator(script, options).then(function(obfuscated) {
  console.log(obfuscated);
}, function(err) {
  console.error(err);
});

**Comment by s-KaiNet** [comment]
javascriptobfuscator.com changed something in their web site. There are no cookies any more. So it fails here `var cookie = res.headers['set-cookie'][0];`  
Is that permanent or not?

**Comment by caiguanhao** [comment]
updated: new version 0.1.1
